### ISSUE TITLE
no jniavutil in java.library.path

### ISSUE THREAD

**Issue by pozemka** [vzhn/bstreamer#3]
When I run windows build using `bserver.bat -c server.yaml` command I get this error:
```
c:\stuff\bstreamer-0.5\bin>bserver.bat -c server.yaml                                            
time     | group    | client connections   | lag         | throughput                            
======================================================================                           
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path     
        at java.lang.ClassLoader.loadLibrary(Unknown Source)                                     
        at java.lang.Runtime.loadLibrary0(Unknown Source)                                        
        at java.lang.System.loadLibrary(Unknown Source)                                          
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)                             
        at org.bytedeco.javacpp.Loader.load(Loader.java:1043)                                    
        at org.bytedeco.javacpp.Loader.load(Loader.java:935)                                     
        at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)                                  
        at me.vzhilin.bstreamer.server.RtspServer.setupLoglevel(RtspServer.java:69)              
        at me.vzhilin.bstreamer.server.RtspServer.start(RtspServer.java:64)                      
        at me.vzhilin.bstreamer.ServerCLI.start(ServerCLI.java:62)                               
        at me.vzhilin.bstreamer.ServerCLI.main(ServerCLI.java:30)                                
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path                        
        at java.lang.ClassLoader.loadLibrary(Unknown Source)                                     
        at java.lang.Runtime.loadLibrary0(Unknown Source)                                        
        at java.lang.System.loadLibrary(Unknown Source)                                          
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1302)                             
        at org.bytedeco.javacpp.Loader.load(Loader.java:1021)                                    
        ... 6 more                                                                               
```

It look like some dependencies missing on my system. Could you please point me to where to get them?

**Comment by pozemka** [comment]
My inattention. I used 32 bit java instead of 64. After installing 64bit version everything works.

Closing.
